### ISSUE TITLE
使用哪个DbUtils编译会有警告。。。怎么破

### ISSUE THREAD

**Issue by TrebleZ** [zyj1609wz/AndroidLiteOrm#1]
Error:(68, 75) 警告: 最后一个参数使用了不准确的变量类型的 varargs 方法的非 varargs 调用;
对于 varargs 调用, 应使用 Object
对于非 varargs 调用, 应使用 Object[], 这样也可以抑制此警告

**Comment by zyj1609wz** [comment]
这个警告可以忽略
